version: '3'
services:
       
   django:
     container_name: django
     labels:
       description: The Dash server
       name: whitebox dash
     ports:
       - "8000:8000"
     volumes:
       - .:/code
     build: './app'
     command: 
       python app/manage.py runserver 0.0.0.0:8000
       
     restart:
       always

     environment: 
       env: payoff

